name: Build

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version"
                required: true
                default: ""

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Setup Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Setup Pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Install Dependencies
              run: pnpm install

            - name: Build
              run: pnpm build "${{ github.event.inputs.version }}"

            - name: Update README
              run: pnpm update-readme

            - name: Commit
              uses: EndBug/add-and-commit@v9
              with:
                  default_author: github_actions
                  message: "chore: update tags"
                  push: true

            - name: Add Repo To Head Of README
              run: echo $'See https://github.com/JacobLinCool/node-prisma-alpine\n\n---\n\n' | cat - README.md > tmp && mv tmp README.md

            - name: Update Docker Hub README
              uses: peter-evans/dockerhub-description@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
                  repository: jacoblincool/node-prisma-alpine
